AAT/Controllers/ClassController.cs
using Microsoft.Office.Interop.Word;
using AAT.Business;
using AAT.Model;
using AAT.Model.Utils;
using AAT.Model.ViewModel;
using AAT.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Ports;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using AAT_SIA.Business;
using AAT.UnisonService;
using System.Text;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.parser;

namespace AAT.Controllers
{
    public class ClassController : BaseController
    {

        public JsonResult UpdateAcknowledgement(string classId, string trainers, string extratrainers)
        {

            if (classId == null || classId.Trim().Length == 0 || (trainers == null && extratrainers == null))
            {
                return Json("success", JsonRequestBehavior.AllowGet);
            }

            try
            {
                string[] trainerIdArr = trainers.Split(',');

                foreach (string trainerId in trainerIdArr)
                {
                    if (!string.IsNullOrEmpty(trainerId))
                    {
                        AcknowledgementService.Instance.CreateNewAcknowledgement(classId, trainerId);
                    }
                }

                if (!string.IsNullOrEmpty(extratrainers))
                {
                    string[] trainerExtraNameArr = extratrainers.Split(',');

                    foreach (string extraTrainerName in trainerExtraNameArr)
                    {
                        AcknowledgementExtraDto dto = new AcknowledgementExtraDto();
                        dto.ClassId = classId;
                        dto.TrainerName = extraTrainerName;
                        dto.AcknowledgementDate = DateTime.Now;
                        AcknowledgementExtraService.Instance.CreateNewAcknowledgementExtra(dto);
                    }
                }

                return Json("success", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ExportPDF(string classID)
        {
            try
            {
                //Step 1: GetData 
                ClassReportDto classReport = ClassService.Instance.GetClassReport(classID);

                //S2: Export Excel
                PdfExport helper = new PdfExport();
                Byte[] fileBytes = helper.ClassExportPdf(classReport);
                string docName = ExportHelper.GetClassExportFilename(classID, FileExtenstion.PDF);
                string mimeType = MimeMapping.GetMimeMapping(docName);

                return File(fileBytes, mimeType, docName);

            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
            }

            return null;
        }

        public ActionResult ExportExcel(string classID)
        {
            try
            {
                //Step 1: GetData 
                ClassReportDto classReport = ClassService.Instance.GetClassReport(classID);

                //S2: Export Excel
                ExcelExport helper = new ExcelExport();
                Byte[] fileBytes = helper.ExportClassExcel(classReport);

                string docName = ExportHelper.GetClassExportFilename(classID, FileExtenstion.EXCEL);
                string mimeType = MimeMapping.GetMimeMapping(docName);
                return File(fileBytes, mimeType, docName);
            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
            }
            return null;
        }

        public ActionResult ExportWord(string classID)
        {
            try
            {
                ExportHelper export = new ExportHelper();
                //Step 1: GetData 
                ClassReportDto classReport = ClassService.Instance.GetClassReport(classID);
                string strBody = export.GetClassHTMLContent(classReport, FileExtenstion.WORD);

                // Force this content to be downloaded 
                // as a Word document with the name of your choice
                string docName = ExportHelper.GetClassExportFilename(classID, FileExtenstion.WORD);
                string mimeType = MimeMapping.GetMimeMapping(docName);
                Response.AppendHeader("Content-Type", "application/msword");
                Response.AppendHeader("Content-disposition", "attachment; filename=" + docName);
                Response.Write(strBody);
            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
            }
            return null;
        }

        public ActionResult ClassList()
        {
            SearchCriterialDto criterial = new SearchCriterialDto
            {
                Page = 1,
                PageSize = ConfigHelper.PageSize
            };

            UserRole role = SessionHelper.Session.User.Role;
            UserType userType = SessionHelper.Session.User.UserType;

            if (role == UserRole.ExternalTrainer || role == UserRole.Staff)
            {
                string trainerInitFilter = "";
                if (userType == UserType.Window)
                {
                    if(!string.IsNullOrEmpty( SessionHelper.Session.User.PersonalNum))
                    {
                        trainerInitFilter = SessionHelper.Session.User.PersonalNum;
                    }
                    else
                    {
                        trainerInitFilter = SessionHelper.Session.User.LoginName;
                    }
                }
                else
                {
                    trainerInitFilter = SessionHelper.Session.User.LoginName;
                }

                if (!string.IsNullOrEmpty(trainerInitFilter))
                {
                    criterial.SearchFieldList.Add(new KeyDto { Key = "TrainerInitFilter", Value = trainerInitFilter });
                }
            }
            //else
            //{
            //    criterial.SearchFieldList.Add(new KeyDto { Key = "ClassDate", Value = DateTime.Now });
            //}

            criterial.SearchFieldList.Add(new KeyDto { Key = "ClassDate", Value = DateTime.Now });

            criterial.SearchFieldList.Add(new KeyDto { Key = "SortColumn", Value = "ClassID" });
            criterial.SearchFieldList.Add(new KeyDto { Key = "SortOrder", Value = "ASC" });
            ClassListViewModel vm = GetClassListViewModel(criterial);
            vm.SortColumn = "ClassID";
            vm.SortOrder = "ASC";
            vm.SearchStatus = 2.ToString();
            vm.SearchDate = DateHelper.FormatDate(DateTime.Now);
            return View(vm);
        }

        // GET: Class/Details/5
        public ActionResult Details(string id, DateTime? reqDate, string staffId = null)
        {
            //LearnerClassDateService srv = new LearnerClassDateService();
            DateTime daterequest = (reqDate != null) ? reqDate.Value : DateTime.Now;

            //ClassViewModel vm = srv.GetClassViewDetailByDate(id, daterequest);
            //vm.ClassDate = daterequest;

            ClassViewModel vm = GetClassViewModel(id, daterequest, "LearnerName", "ASC", "CheckInTime", "DESC");
            return View(vm);
        }

        private ClassListViewModel GetClassListViewModel(SearchCriterialDto criterial)
        {
            ClassListViewModel vm = new ClassListViewModel();
            ClassService srv = new ClassService();
            int totalRecord = 0;

            List<KeyDto> roleFilters = FilterHelper.Instance.GetFilterClassListPage(criterial);
            criterial.SearchFieldList.AddRange(roleFilters);
            vm.ClassList = srv.GetClassList(criterial, ref totalRecord);

            if (criterial.Page != null && criterial.PageSize != null)
            {
                PageViewModel paging = new PageViewModel(criterial.Page.Value,
                    criterial.PageSize.Value, totalRecord, "CardClassPaging");
                vm.PagingModel = paging;
            }

            return vm;
        }

        public JsonResult RFIDAttendingUpdate(string classId, DateTime classDate, string cardId)
        {
            //if (classId == null || classId.Trim().Length == 0 || trainers == null || trainers.Trim().Length == 0)
            //{
            //    return Json("success", JsonRequestBehavior.AllowGet);
            //}

            try
            {
                CardDto re = new CardDto();
                re.Status = "Learner Invalid!";
                byte[] photo;
                //TODO TESTING
                //photo = ImageHelper.GetDemoPhotoByteArray();
                //re.Base64Image = "data:image/gif;base64," + ImageHelper.ConvertToBase64FromByteArr(photo);

                //if (!string.IsNullOrEmpty(cardId))
                //{
                //    //Card Image 
                //    cardId = cardId.Trim();
                //    re.StaffId = cardId;

                //    LearnerDto learner = LearnerService.Instance.GetLearnerById(re.StaffId);
                //    if (learner != null)
                //    {
                //        re.Name = learner.LearnerName;

                //        SearchCriterialDto criterial = new SearchCriterialDto();
                //        criterial.SearchFieldList.Add(new KeyDto { Key = "ClassId", Value = classId });
                //        criterial.SearchFieldList.Add(new KeyDto { Key = "ClassDate", Value = DateTime.Now });
                //        int totalRecord = 0;

AAT/Views/Class/ClassList.cshtml
@using Newtonsoft.Json
@using AAT.Model
@using AAT.Model.Utils
@using AAT.Utils

@model AAT.Model.ViewModel.ClassListViewModel
@using (Html.BeginForm("ClassListAction", "Class", FormMethod.Post, new { @id = "ClassForm" }))
{
<div class="pagedetail-container">

	<div style="width:100%;" class="bottomborder"><span id="criterialCollapselnk"><img id="imgCriterialCollapse" class="collapseImg" src="~/Images/expand.svg" /> &nbsp;Criteria</span></div>

	<div id="tbCriterial" style="margin-top:15px; padding-bottom:3px;" class="">
		@if (SessionHelper.Session.User.Role != AAT.Model.Utils.UserRole.ExternalTrainer)
		{
			<table style="width:100%;">
				<tr>
					<td class="colCriterialLabel">Class ID</td>
					<td>
						@Html.TextBox("txtClassId", @Model.SearchClassId)
					</td>
					<td class="colCriterialLabel">Course ID</td>
					<td><input type="text" id="txtCourseId" name="txtCourseId" value="@Model.SearchCourseId" /></td>
					<td class="colCriterialLabel">Instructor ID</td>
					<td><input type="text" id="txtTrainerId" name="txtTrainerId" value="@Model.SearchTrainerId" /></td>
					<td class="colCriterialLabel">Start Date</td>
					<td style="display:inline; white-space:nowrap;">
						<input id="txtStartDate" name="txtStartDate" type="text" readonly="readonly" class="datetext" value="@Model.SearchStartDate" />
						<img id="btnStartDate" class="svgSearchBtn" src="~/Images/calendar.svg">
					</td>
				</tr>
				<tr style="margin-top:7px; height:40px;">
					<td class="colCriterialLabel">Status
					<td>
						<select style="width:120px; height:25px;" id="ddlStatus" name="ddlStatus">
							<option @Html.Raw(Model.SearchStatus == "" ? "selected" : "") value="">All</option>
							<option @Html.Raw(Model.SearchStatus == "1" ? "selected" : "") value="1">New</option>
							<option @Html.Raw(Model.SearchStatus == "2" ? "selected" : "") value="2">Ongoing</option>
							<option @Html.Raw(Model.SearchStatus == "3" ? "selected" : "") value="3">Pending acknowledgement</option>
							<option @Html.Raw(Model.SearchStatus == "4" ? "selected" : "") value="4">Completed</option>
						</select>
					</td>
					<td class="colCriterialLabel">Course Name</td>
					<td><input type="text" id="txtCourseName" name="txtCourseName" value="@Model.SearchCourseName" /></td>
					<td class="colCriterialLabel">Instructor Name</td>
					<td><input type="text" id="txtTrainerName" name="txtTrainerName" value="@Model.SearchTrainerName" /></td>
					<td class="colCriterialLabel">End Date</td>
					<td>
						<input id="txtEndDate" name="txtEndDate" type="text" readonly="readonly" class="datetext" value="@Model.SearchEndtDate" />
						<img id="btnEndDate" class="svgSearchBtn" src="~/Images/calendar.svg">
					</td>
				</tr>
			</table>
			<div style="width:100%; text-align:right; ">
				<input id="btnSearch" type="button" value="Search" class="btn btn-outline-primary" />
				<input id="btnClear" type="button" value="Clear" class="btn btn-outline-primary" />
			</div>
		}
		else
		{
			<div style="width:100%; text-align:center;display:inline-block;">
				<span class="colCriterialLabel">Class ID</span>
				@Html.TextBox("txtClassId", @Model.SearchClassId)
				<input id="btnSearch" type="button" value="Search" class="btn btn-outline-primary" style="margin-left:10px;" />
			</div>
		}
	</div>
	@Html.Hidden("Page")
	@Html.Hidden("PageSize", Model.PagingModel.Pager.PageSize)
	@Html.Hidden("hidCourseId", Model.SearchCourseId)
	@Html.Hidden("hidCourseName", Model.SearchCourseName)
	@Html.Hidden("hidClassId", Model.SearchClassId)
	@Html.Hidden("hidClassName", Model.SearchClassName)
	@Html.Hidden("hidTrainerId", Model.SearchTrainerId)
	@Html.Hidden("hidTrainerName", Model.SearchTrainerName)
	@Html.Hidden("hidDate", Model.SearchDate)
	@Html.Hidden("hidStartDate", Model.SearchStartDate)
	@Html.Hidden("hidEndDate", Model.SearchEndtDate)
	@Html.Hidden("hidSearchStatus", Model.SearchStatus)
	@Html.Hidden("hidSortColumn", Model.SortColumn)
	@Html.Hidden("hidSortOrder", Model.SortOrder)
	@Html.Hidden("ActionId")

	<br />

    <table class="listview-tb">
        <tbody style="
    overflow-x: auto;
    box-shadow: 0 0 black;
    display: block;
    width: 99vw;
    min-width:99vw;">
            <tr class="headder-row">
                <td class="classlist-table-classID">
                    Class ID
                    <img id="sortClassID" onclick="DoSorting('ClassID')" src="~/images/expand.svg" class="imgSortToggle" />
                </td>
                <td class="classlist-table-courseName">
                    Course Name
                    <img id="sortCourseName" onclick="DoSorting('CourseName')" src="~/images/expand.svg" class="imgSortToggle" />
                </td>
                <td style="" class="classlist-table-courseID">
                    Course ID
                    <img id="sortCourseId" onclick="DoSorting('CourseId')" src="~/images/expand.svg" class="imgSortToggle" />
                </td>
                <td class="classlist-table-instructorId">
                    Instructor ID
                    <img id="sortTrainersId" onclick="DoSorting('TrainerIDs')" src="~/images/expand.svg" class="imgSortToggle" />
                </td>
                <td class="classlist-table-instructor">
                    Instructor Name
                    <img id="sortTrainers" onclick="DoSorting('Trainers')" src="~/images/expand.svg" class="imgSortToggle" />
                </td>
                <td style="text-align:center;" class="classlist-table-startDate">
                    Start Date
                    <img id="sortStartDate" onclick="DoSorting('StartDate')" src="~/images/expand.svg" class="imgSortToggle" />
                </td>
                <td style="text-align:center;" class="classlist-table-endDate">
                    End Date
                    <img id="sortEndDate" onclick="DoSorting('EndDate')" src="~/images/expand.svg" class="imgSortToggle" />
                </td>
                <td class="classlist-table-Status">
                    Status
                    <img id="sortClassStatusID" onclick="DoSorting('ClassStatusID')" src="~/images/expand.svg" class="imgSortToggle" />
                </td>
                <td class="classlist-table-export"></td>
            </tr>
            @if (Model.ClassList.Count > 0)
            {
                foreach (var item in Model.ClassList)
                {
                    string classLink = "/Class/Details?id=" + @item.ClassID.ToString();
                    string classTime = "/Class/Timing?id=" + @item.ClassID.ToString();

                    <tr class="smalltr">
                        @*ON Goin*@

                        <td class="classlist-table-classID text-overflow">
                            @if (SessionHelper.Session.User.Role == AAT.Model.Utils.UserRole.Admin || SessionHelper.Session.User.Role == AAT.Model.Utils.UserRole.SuperAdmin)
                            {
                                if (DateHelper.FormatDateMonthInName(item.EndDate) == DateTime.Now.ToString("dd MMM yyyy") || item.ClassStatusID == ClassStatus.OnGoing.GetHashCode()
                                    || item.ClassStatusID == ClassStatus.PendingAcknowledge.GetHashCode())
                                {
                                    <a href="@classLink">@item.ClassID</a>
                                }
                                else
                                {
                                    @item.ClassID
                                }
                            }
                            else
                            {
                                if (item.ClassStatusID == ClassStatus.OnGoing.GetHashCode()
                                || item.ClassStatusID == ClassStatus.PendingAcknowledge.GetHashCode())
                                {
                                    <a href="@classLink">@item.ClassID</a>
                                }
                                else
                                {
                                    @item.ClassID
                                }
                            }
                        </td>

                        <td class="classlist-table-courseName text-overflow" title="@item.CourseName">@item.CourseName</td>
                        <td style="" class="classlist-table-courseID text-overflow">@item.CourseId</td>
                        <td class="classlist-table-instructorId text-overflow" title="@item.TrainerIDs">
                            @item.TrainerIDs
                        </td>
                        <td class="classlist-table-instructor text-overflow" title="@item.Trainers">
                            @item.Trainers
                        </td>
                        <td style="text-align:center;" class="classlist-table-startDate text-overflow">@DateHelper.FormatDateMonthInName(item.StartDate)</td>
                        <td style="text-align:center;" class="classlist-table-endDate text-overflow">@DateHelper.FormatDateMonthInName(item.EndDate)</td>
                        <td class="classlist-table-StatusAction text-overflow">@EnumsHelper.GetClassStatusString(item.ClassStatusID)</td>
                        <td class="classlist-table-export action-col" style="text-align:right; padding-right:10px;">
                            @if (item.ClassStatusID == ClassStatus.Completed.GetHashCode())
                            {
                                <a href="@classTime"><img class="action-img-btn" src="~/Images/hour_entry.svg" /></a>
                                <img onclick="
									 ExportPDF('@item.ClassID');" id="btnPdf" class="export-img-btn" src="~/Images/pdf.jpg">
                                <img onclick="ExportExcel('@item.ClassID');" id="btnExcel" class="export-img-btn" src="~/Images/excel.png">
                                <img onclick="ExportWord('@item.ClassID');" id="btnWorld" class="export-img-btn" src="~/Images/word.png">
                            }
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="smalltr">
                    <td colspan="9" style="text-align:center">No record found!</td>
                </tr>
            }
            </tbody>
    </table>
	<div>
		@Html.Partial("~/Views/Shared/Pager.cshtml", Model.PagingModel)
	</div>
</div>
}
<script>

	
	$(function () {
		$("#txtStartDate").datepicker({dateFormat: '@DateHelper.JqueryDatePickerFormat'});
		$("#txtEndDate").datepicker({ dateFormat: '@DateHelper.JqueryDatePickerFormat' });

		//Sorting
		var imgSortName = "#sort" + "@Model.SortColumn";
		var imgSortSrc = "../images/expand_active.svg";

		if ("@Model.SortOrder.ToUpper()" !== "ASC") {
			imgSortSrc = "../images/collapse_active.svg";
		}

		$(imgSortName).attr("src", imgSortSrc);
	});

	function DoSorting(SortColumn) {

		var SortOrder = "ASC";
		if ("@Model.SortColumn" === SortColumn && "@Model.SortOrder.ToUpper()" === "ASC") {
			SortOrder = "DESC";
		}

		$("#ActionId").val(@PageAction.Sorting.GetHashCode());
		$("#hidSortColumn").val(SortColumn);
		$("#hidSortOrder").val(SortOrder);

		$("#ClassForm").submit();
	}

	$("#btnClear").click(function () {
		$("#txtClassId").val("");
		$("#txtCourseId").val("");
		$("#txtTrainerId").val("");
		$("#txtStartDate").val("");
		$("#ddlStatus").val("");
		$("#txtCourseName").val("");
		$("#txtTrainerName").val("");
        $("#txtEndDate").val("");

        GoURL("/Class/ClassList");
	});


	function ExportPDF(classId) {
		window.location.href = "/Class/ExportPDF?classID=" + classId;
	}

	function ExportWord(classId) {
		window.location.href = "/Class/ExportWord?classID=" + classId;
	}

	function ExportExcel(classId) {
		window.location.href = "/Class/ExportExcel?classID=" + classId;
	}

	$("#btnStartDate").click(function () {
		$("#txtStartDate").focus();
	});

	$("#btnEndDate").click(function () {
		$("#txtEndDate").focus();
	});

	$("#btnSearch").click(function () {
		$("#ActionId").val(2);
		$("#ClassForm").submit();
	});

	function CardClassPaging(page) {
		$("#ActionId").val(1);
		$("#Page").val(page);
		$("#ClassForm").submit();
	}

	$("#criterialCollapselnk").click(function () {
		criterialCollapse();
	});

	function criterialCollapse() {
		var criterialImg = $('#imgCriterialCollapse');
		var tbCriterial = $('#tbCriterial');
		var imgeSrouce = $('#imgCriterialCollapse').attr('src');

		if (imgeSrouce.indexOf("expand.svg") >= 0) {
			$(criterialImg).attr("src", "/Images/collapse.svg");
			tbCriterial.addClass("hideDisplay");
		}
		else {
			$(criterialImg).attr("src", "/Images/expand.svg");
			tbCriterial.removeClass("hideDisplay");
		}
	}
</script>