AAT/Controllers/LearnerController.cs
using AAT.Business;
using AAT.Model;
using AAT.Model.Utils;
using AAT.Model.ViewModel;
using AAT.UnisonService;
using AAT.Utils;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AAT.Controllers
{
    public class LearnerController : BaseController
    {
        public ActionResult ExportPDF(string classID, string staffId)
        {
            try
            {
                //Step 1: GetData 
                LearnerPresentViewModel vm = LearnerService.Instance.GetLearnerPresentViewModel(classID, staffId);

                //S2: Export Excel
                PdfExport helper = new PdfExport();
                Byte[] fileBytes = helper.LearnExportPdf(vm);
                string docName = classID + "_" + staffId + ".pdf";
                string mimeType = MimeMapping.GetMimeMapping(docName);

                return File(fileBytes, mimeType, docName);

            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
            }

            return null;
        }

        public ActionResult LearnerList_ExportPDF(List<LearnerDto> learnerList, SearchCriterialDto criterial)
        {
            try
            {

                ExportHelper export = new ExportHelper();
                string html_string = export.GetLearnerHistoryHTML(learnerList, criterial, FileExtenstion.PDF);

                //S2: Export Excel
                PdfExport helper = new PdfExport();
                Byte[] fileBytes = helper.GetPDFBytes(html_string);
                string docName = "Learner_" + learnerList[0].StaffID + ".pdf";
                string mimeType = MimeMapping.GetMimeMapping(docName);

                return File(fileBytes, mimeType, docName);

            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
            }

            return null;
        }

        public ActionResult LearnerList_ExportExcel(List<LearnerDto> learnerList, SearchCriterialDto criterial)
        {
            try
            {
                //S2: Export Excel
                ExcelExport helper = new ExcelExport();
                Byte[] fileBytes = helper.ExportLearnerHistory(learnerList, criterial);
                string docName = "Learner_" + learnerList[0].StaffID + ".xlsx";

                string mimeType = MimeMapping.GetMimeMapping(docName);
                return File(fileBytes, mimeType, docName);
            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
            }

            return null;
        }

        public ActionResult LearnerList_ExportWord(List<LearnerDto> learnerList, SearchCriterialDto criterial)
        {
            try
            {

                ExportHelper export = new ExportHelper();
                string strBody = export.GetLearnerHistoryHTML(learnerList, criterial, FileExtenstion.WORD);

                // Force this content to be downloaded 
                // as a Word document with the name of your choice
                string docName = "Learner_" + learnerList[0].StaffID + ".doc";
                string mimeType = MimeMapping.GetMimeMapping(docName);
                Response.AppendHeader("Content-Type", "application/msword");

                Response.AppendHeader("Content-disposition", "attachment; filename=" + docName);
                Response.Write(strBody);

            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
            }

            return null;
        }

        public ActionResult ExportExcel(string classID, string staffId)
        {
            try
            {
                //Step 1: GetData 
                LearnerPresentViewModel vm = LearnerService.Instance.GetLearnerPresentViewModel(classID, staffId);

                //S2: Export Excel
                ExcelExport helper = new ExcelExport();
                Byte[] fileBytes = helper.ExportLearner(vm);
                string docName = classID + "_" + staffId + ".xlsx";
                string mimeType = MimeMapping.GetMimeMapping(docName);

                return File(fileBytes, mimeType, docName);
                 
            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
            }

            return null;
        }

        public ActionResult ExportWord(string classID, string staffId)
        {
            try
            {
                ExportHelper export = new ExportHelper();
                //Step 1: GetData 
                LearnerPresentViewModel vm = LearnerService.Instance.GetLearnerPresentViewModel(classID, staffId);
                string strBody = export.GetLearnerHTML(vm, FileExtenstion.WORD);

                // Force this content to be downloaded 
                // as a Word document with the name of your choice
                string docName = classID + "_" + staffId + ".doc";
                string mimeType = MimeMapping.GetMimeMapping(docName);
                Response.AppendHeader("Content-Type", "application/msword");

                Response.AppendHeader("Content-disposition", "attachment; filename=" + docName);
                Response.Write(strBody);

            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
            }

            return null;
        }

        // GET: Learner
        public ActionResult LearnerList()
        {
            if (SessionHelper.Session.User.Role == UserRole.ExternalTrainer ||
                SessionHelper.Session.User.Role == UserRole.Staff)
            {
                return RedirectToAction("ClassList", "Class");
            }

            SearchCriterialDto criterial = new SearchCriterialDto
            {
                Page = 1,
                PageSize = ConfigHelper.PageSize
            };

            criterial.SearchFieldList.Add(new KeyDto { Key = "SortColumn", Value = "StaffID" });
            criterial.SearchFieldList.Add(new KeyDto { Key = "SortOrder", Value = "ASC" });

            LearnerListViewModel vm = GetLearnerListViewModel(criterial);

            vm.SortColumn = "StaffID";
            vm.SortOrder = "ASC";
            return View(vm);
        }

        private LearnerListViewModel GetLearnerListViewModel(SearchCriterialDto criterial)
        {
            LearnerListViewModel vm = new LearnerListViewModel();
            LearnerService srv = new LearnerService();

            int totalRecord = 0;
            vm.LearnerList = srv.GetLearnerList(criterial, ref totalRecord);

            if (criterial.Page != null && criterial.PageSize != null)
            {
                PageViewModel paging = new PageViewModel(criterial.Page.Value,
                    criterial.PageSize.Value, totalRecord, "LearnerListPaging");
                vm.PagingModel = paging;
            }

            return vm;
        }

        public ActionResult LearnerListAction(FormCollection collection)
        {
            try
            {
                if (String.IsNullOrWhiteSpace(collection["ActionId"]))
                {
                    return null;
                }

                int actionId = int.Parse(collection["ActionId"]);
                string searchStartDate = string.Empty;
                string searchEndDate = string.Empty;
                string searchCourseId = string.Empty;
                string searchCourseName = string.Empty;
                string searchClassId = string.Empty;
                string searchStaffId = string.Empty;
                string searchLearnerName = string.Empty;
                string searchStatus = string.Empty;
                string sortColumn = string.Empty;
                string sortOrder = string.Empty;

                SearchCriterialDto criterial = new SearchCriterialDto();
                #region Action Type
                if (actionId == (int)PageAction.Pagging)
                {
                    if (String.IsNullOrWhiteSpace(collection["Page"]))
                    {
                        return null;
                    }

                    criterial.Page = Int16.Parse(collection["Page"]);
                    criterial.PageSize = ConfigHelper.PageSize;
                    searchStartDate = collection["hidStartDate"];
                    searchEndDate = collection["hidEndDate"];
                    searchCourseId = collection["hidCourseId"];
                    searchCourseName = collection["hidCourseName"];
                    searchClassId = collection["hidClassId"];
                    searchStaffId = collection["hidStaffId"];
                    searchLearnerName = collection["hidLearnerName"];
                    searchStatus = collection["hidSearchStatus"];
                    sortColumn = collection["hidSortColumn"];
                    sortOrder = collection["hidSortOrder"];
                }
                else if (actionId == (int)PageAction.Search)
                {
                    criterial.Page = 1;
                    criterial.PageSize = ConfigHelper.PageSize;
                    searchStartDate = collection["txtStartDate"];
                    searchEndDate = collection["txtEndDate"];
                    searchCourseId = collection["txtCourseId"];
                    searchCourseName = collection["txtCourseName"];
                    searchClassId = collection["txtClassId"];

AAT/Views/Learner/Details.cshtml
@using AAT.Utils
@using AAT.Model
@using AAT.Model.Utils
@model AAT.Model.ViewModel.LearnerPresentViewModel

@{
    ViewBag.Title = "Home Page";
    string currentDate = DateHelper.FormatDateMonthInName(DateTime.Now);
    string successText = (Model.Learner.Success == "Y") ? "Yes" : "No";
    string staffId = Model.Learner.StaffID.ToString();
}

@using (Html.BeginForm("EditLearnerSuccessfulStatusAction", "Learner", FormMethod.Post, new { @id = "editLearnerSucessfulStatusForm" }))
{
    <div style="width: 100%; min-width:800px;">
        <div class="back-container">
            <a href="#" onclick="GoBack();"><div class="btn-back btn-back-learner-details"> < Back </div></a>
        </div>
        @Html.Hidden("hidLearnerSuccess", Model.Learner.Success)
        @Html.Hidden("hidLearnerSuccessRemark", Model.Learner.SuccessRemark)
        @Html.Hidden("hidSuccessText", successText)
        @Html.Hidden("hidStaffID", staffId)
        @Html.Hidden("hidClassID",Model.Class.ClassID)
        @Html.Hidden("ActionId")
        @Html.Hidden("hidEditLearnerStatusAction")
        <FIELDSET style="margin-left:22px;margin-right:22px;">
            <LEGEND>Class Summary</LEGEND>
            <table style="width:100%;">
                <colgroup>
                    <col width="100" />
                </colgroup>
                <tr>
                    <td class="label-col">Class ID </td>
                    <td class="SummaryText">@Model.Class.ClassID</td>
                    <td class="label-col">Course ID</td>
                    <td class="SummaryText">@Model.Class.CourseId</td>
                    <td class="label-col">Start Date</td>
                    <td class="SummaryText">@DateHelper.FormatDateMonthInName(Model.Class.StartDate)</td>
                    <td class="label-col">End Date</td>
                    <td class="SummaryText">@DateHelper.FormatDateMonthInName(Model.Class.EndDate)</td>
                </tr>
				<tr>
					<td class="label-col">Status</td>
					<td class="SummaryText">@EnumsHelper.GetClassStatusString(Model.Class.ClassStatusID)</td>
					<td class="label-col" style="white-space:nowrap;">Course Name</td>
					<td class="SummaryText" colspan="3">@Model.Class.CourseName</td>
					@if (!string.IsNullOrEmpty(Model.Learner.SuccessRemark))
					{
						<td class="label-col">Updated By</td>
						<td class="SummaryText">@Model.Learner.UpdateBy</td>
					}
					else
					{
						<td></td>
						<td></td>
					}
				</tr>
				<tr>
					<td class="label-col" colspan="1" style="vertical-align:middle">
						<span>Instructor:</span>
					</td>
					<td class="SummaryText" colspan="3" style="vertical-align:middle">
						@{
							string trainerlist = String.Join(", ", Model.Class.TrainerList.Select(x => x.TrainerName).ToArray());
							<span style="display:inline-block;">@trainerlist</span>
						}
					</td>
					<td class="label-col">Successful</td>
					<td id="successfulStatus" class="SummaryText">
						@successText
						@if (Model.Class.EndDate.Value.Date == DateTime.Now.Date && (SessionHelper.Session.User.Role == UserRole.Admin ||
							SessionHelper.Session.User.Role == UserRole.SuperAdmin))
						{
							<span class="btn-edit-ack" onclick="EditLearnerSuccessStatus()"> <i class="far fa-edit"></i> </span>

						}
					</td>
					@if (!string.IsNullOrEmpty(Model.Learner.SuccessRemark))
					{
					<td class="label-col">Remark</td>
						<td class="SummaryText"> <span class="learner-remark-sum" title="@Model.Learner.SuccessRemark">@Model.Learner.SuccessRemark</span></td>
					}
					else
					{
						<td></td>
						<td></td>
					}


				</tr>
            </table>
        </FIELDSET>
        <p>&nbsp;</p>
        <div id="container">

            <table style="width:100%; table-layout:fixed; ">
                <tr>
                    <td class="col-md-2" style="vertical-align:top; padding-top:10px;">
                        <div style="height:300px; background-color:#eee;border-radius: 12px; ">

                            <br />

                            <table style="width:100%; margin-top:15px;">
                                <tr>
                                    <td style="text-align:center;">
                                        @if (!string.IsNullOrEmpty(Model.Learner64ImageString))
                                        {
                                            <img class="verifyphoto" src="@Model.Learner64ImageString" />
                                        }
                                        else
                                        {
                                            <img class="verifyphoto" src="~/Images/me.png" />
                                        }
                                    </td>
                                </tr>
                                <tr style="height:27px;">

                                    <td style="text-align:center;">@Model.Learner.LearnerName</td>
                                </tr>
                                <tr style="height:27px;">

                                    <td style="text-align:center;">@Model.Learner.StaffID</td>
                                </tr>
                            </table>
                        </div>


                    </td>
                    <td class="col-md-6" style="padding-right:45px;  white-space:nowrap;  vertical-align: top;">
                        <br />
                        <div id="timmingContainer" style="width:100%;margin-left:10px; margin-right:10px;">
                            @*<div style="width:100%;" class="bottomborder">Learner Details</div>*@
                            <table class="listview-tb" style="width:100%;">
                                <colgroup>
                                    <col />
                                    <col style="text-align:center" />
                                    <col style="text-align:center" />
                                    <col />
                                </colgroup>
                                <tr>
                                    <td colspan="2" style="padding-left:0px; padding-bottom: 0px;">Learner Details</td>
                                    <td colspan="4" style="text-align:right; padding-bottom: 0px;"></td>
                                </tr>
								<tr class="headder-row">
									<td>Date</td>
									<td style="text-align:center">Present</td>
									<td style="text-align:center">Absent</td>
									<td>Time In</td>
									<td  class="remark-field-update">Remarks</td>
									<td>Updated By</td>
								</tr>
                                @foreach (var item in Model.LearnerClassDates)
                                {
								<tr class="smalltr">
									<td>@DateHelper.FormatDateMonthInName(item.ClassDate)</td>
									@if (item.CheckInTime != null)
									{
										<td style="text-align:center">
											<img src="~/Images/check.svg" class="img-check" />
										</td>
										<td></td>
										<td>@DateHelper.FormatTime(item.CheckInTime)</td>
										<td class="remark-field-update">@item.Remark</td>
										<td>@item.UpdateBy</td>
									}
									else
									{
										<td></td>
										<td style="text-align:center"><img src="~/Images/check-red.svg" class="img-check" /></td>
										<td></td>
										<td></td>
										<td></td>
									}



								</tr>
                                }
                            </table>
                        </div>

                    </td>
                </tr>
            </table>
            <div id="left" class="col col-xs-6 text-left" style="max-width:350px;">


            </div>
            <div id="center" class="col col-xs-6 text-left" style="">


            </div>
        </div>
        <div style="clear:both;"></div>

    </div>
}
    <!-- The Edit Learner Successful Status Modal -->
    <div id="editLearnerSuccessModel" class="modal">
        <!-- Modal content -->
		<div class="modal-content" style="width:500px;">
			<div class="col-lg-12">
				<div class="leftDiv"><b>Edit Learner Status </b></div>
				<div class="rightDiv "><span class="close" onclick="CloseModelLearnerSuccessful();">&times;</span></div>
			</div>
			<div class="col-lg-12">
				<br />
				&nbsp; Successful Status: &nbsp;&nbsp;<input type="radio" id="rdbSuccessful" name="rdbSuccessfulStatus" value="Y" />&nbsp;&nbsp;Yes&nbsp;&nbsp;
				<input type="radio" id="rdbUnsuccessful" name="rdbSuccessfulStatus" value="N" />&nbsp;&nbsp;No
			</div>
			
			<div class="col-lg-12">
				<br/>
				&nbsp; Remark: <br />
				<textarea id="statusRemark" name="statusRemark" rows="7" maxlength="500" 
						  style="width:100%; margin:5px;"></textarea>
			</div>
			<div style="width:100%; text-align:right;">
				<input type="button" id="btnModelEditLearnerSucessfulSave" value="Submit" class="btn btn-outline-primary" />
				<input type="button" id="btnModelCloseLearnerSucessful" value="Cancel" class="btn btn-outline-primary" onclick="CloseModelLearnerSuccessful();" />
			</div>
		</div>

    </div>

	<script>

     $(function () {
        $(".btn-back").click(function () {
            parent.history.back();
            return false;
        });
    });

	$(function () {

        if ($("#hidSuccessText").val() == "Yes") {
            $("#successfulStatus").addClass("sucessfulStatus-green");
        } else {
            $("#successfulStatus").addClass("sucessfulStatus-red");
        }

	});

		function ShowLearnerSuccessModel() {
			$("#statusRemark").val("@Model.Learner.SuccessRemark");
			var modal = document.getElementById('editLearnerSuccessModel');
			modal.style.display = "block";
	}

	function GoBack() {
		window.location.href = "/Class/Timing?id=@Model.Class.ClassID";
    }

    function CloseModelLearnerSuccessful() {
        var modal = document.getElementById('editLearnerSuccessModel');
        modal.style.display = "none";
    }

    function EditLearnerSuccessStatus()
    {
        var success_text = $("#hidSuccessText").val();
        ShowLearnerSuccessModel();
        if (success_text == "Yes") {
            $("#rdbSuccessful").prop("checked", true);
            $("#rdbUnsuccessful").prop("checked", false);
        } else {
            $("#rdbSuccessful").prop("checked", false);
            $("#rdbUnsuccessful").prop("checked", true);
        }


		//var testvalue = $("#hidLearnerClassDateId").val();
        $("#hidEditLearnerStatusAction").val('EDIT');
	}

    $('#btnModelEditLearnerSucessfulSave').click(function () {

		var remark = $("#statusRemark").val();

		if ($.trim(remark).length === 0) {
			alert("Please input remark!");
			return;
		}

		var learner_status = $("input[name='rdbSuccessfulStatus']:checked").val();
		var orgRemark = $("#hidLearnerSuccessRemark").val();
		var orgStatus = $("#hidLearnerSuccess").val();

		if (learner_status !== orgStatus || orgRemark !== remark) {

			$("#hidLearnerSuccessRemark").val(remark);
			$("#hidLearnerSuccess").val(learner_status);
			$("#ActionId").val(@PageAction.Update.GetHashCode());
			$("#editLearnerSucessfulStatusForm").submit();
		}
		else {
			CloseModelLearnerSuccessful();
		}
        //window.location.reload(true);
    });
	</script>