AAT/Controllers/DepartmentController.cs
using AAT.Business;
using AAT.Model;
using AAT.Model.Utils;
using AAT.Model.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AAT.Controllers
{
    public class DepartmentController : BaseController
    {
        // GET: Department
        public ActionResult DepartmentList()
        {
            if (SessionHelper.Session.User.Role == UserRole.ExternalTrainer ||
                SessionHelper.Session.User.Role == UserRole.Staff)
            {
                return RedirectToAction("ClassList", "Class");
            }

            SearchCriterialDto criterial = new SearchCriterialDto
            {
                Page = 1,
                PageSize = 999
            };
            DepartmentListViewModel vm = GetDepartmentListViewModel(criterial);
            return View(vm);
        }

        public ActionResult DepartmentListAction(FormCollection collection)
        {
            try
            {
                if (String.IsNullOrWhiteSpace(collection["ActionId"]))
                {
                    return null;
                }

                int actionId = int.Parse(collection["ActionId"]);
                string searchDepartmentId = string.Empty;
                string searchDepartmentName = string.Empty;
                SearchCriterialDto criterial = new SearchCriterialDto();

                if (actionId == (int)PageAction.Search)
                {
                    criterial.Page = 1;
                    criterial.PageSize = ConfigHelper.PageSize;
                    searchDepartmentId = collection["txtDepartmentId"];
                    searchDepartmentName = collection["txtDepartmentName"];
                }

                if (!String.IsNullOrWhiteSpace(searchDepartmentId))
                {
                    criterial.SearchFieldList.Add(new KeyDto { Key = "DepartmentId", Value = searchDepartmentId });
                }

                if (!String.IsNullOrWhiteSpace(searchDepartmentName))
                {
                    criterial.SearchFieldList.Add(new KeyDto { Key = "DepartmentName", Value = searchDepartmentName });
                }

                //Get Data
                DepartmentListViewModel vm = GetDepartmentListViewModel(criterial);
                vm.SearchId = searchDepartmentId;
                vm.SearchName = searchDepartmentName;

                return View("DepartmentList", vm);
            }
            catch (Exception ex)
            {
                LogHelper.Error(System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
                return null;
            }
        }

        private DepartmentListViewModel GetDepartmentListViewModel(SearchCriterialDto criterial)
        {
            DepartmentListViewModel vm = new DepartmentListViewModel();
            DepartmentService srv = new DepartmentService();

            int totalRecord = 0;
            vm.DepartmentList = srv.GetDepartmentList(criterial, ref totalRecord);

            //if (criterial.Page != null && criterial.PageSize != null)
            //{
            //    PageViewModel paging = new PageViewModel(criterial.Page.Value,
            //        criterial.PageSize.Value, totalRecord, "DepartmentListPaging");
            //    vm.PagingModel = paging;
            //}

            return vm;
        }



        // GET: Department/Create
        [HttpPost]
        public ActionResult Update(FormCollection collection)
        {
            try
            {
                if (SessionHelper.Session.User.Role == UserRole.ExternalTrainer ||
                SessionHelper.Session.User.Role == UserRole.Staff)
                {
                    return RedirectToAction("ClassList", "Class");
                }

                var oldDepartmentId = collection["hidDepartmentId"];
                DepartmentDto dto = new DepartmentDto();

                if (!String.IsNullOrEmpty(oldDepartmentId)) //Update
                {
                    SearchCriterialDto criterial = new SearchCriterialDto { Page = 1, PageSize = 1 };
                    criterial.SearchFieldList.Add(new KeyDto { Key = "DepartmentIds", Value = oldDepartmentId });
                    int totalRecord = 0;

                    dto = DepartmentService.Instance.GetDepartmentList(criterial, ref totalRecord).FirstOrDefault();
                    if (dto == null)
                    {
                        RedirectToAction("Login", "Account");
                    }

                }
                dto.DepartmentId = collection["txtDepartmentID"];
                dto.DepartmentName = collection["txtDepartmentName"];


                if (!String.IsNullOrEmpty(oldDepartmentId))
                {
                    //If departmentId change -> Check whether deparment have any existed course
                    if (!string.IsNullOrEmpty(oldDepartmentId) && oldDepartmentId != dto.DepartmentId)
                    {
                        int existedCourse = DepartmentService.Instance.GetNumberDepartmentCourse(oldDepartmentId);

                        if (existedCourse > 0)
                        {
                            RedirectToAction("Login", "Account");
                        }
                    }

                    DepartmentService.Instance.UpdateDepartment(dto, oldDepartmentId);
                }
                else
                {
                    DepartmentService.Instance.CreateNewDepartment(dto);
                }
                return RedirectToAction("DepartmentList");
            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
                return View();
            }
        }

        // GET: Department/Edit/5
        public ActionResult DepartmentUpdate(string id = null)
        {
            DepartmentDto vm = new DepartmentDto();

            if (!string.IsNullOrEmpty(id)) //Update 
            {
                SearchCriterialDto criterial = new SearchCriterialDto { Page = 1, PageSize = 1 };
                criterial.SearchFieldList.Add(new KeyDto { Key = "DepartmentIds", Value = id });
                int totalRecord = 0;

                var department = DepartmentService.Instance.GetDepartmentList(criterial, ref totalRecord).FirstOrDefault();

                if (department != null)
                {
                    vm = department;
                }
            }

            return View(vm);
        }

        public JsonResult CheckExistedDepartmentId(string departmentId, string originalId)
        {
            try
            {
                if (originalId == string.Empty || originalId != departmentId)
                {
                    //If departmentId change -> Check whether deparment have any existed course
                    if (!string.IsNullOrEmpty( originalId) && originalId != departmentId)
                    {
                        int existedCourse = DepartmentService.Instance.GetNumberDepartmentCourse(originalId);

                        if(existedCourse > 0)
                        {
                            string msg = "Unable edit Department ID. There are existed Courses under This Department!";
                            return Json(msg, JsonRequestBehavior.AllowGet);
                        }
                    }

                    SearchCriterialDto criterial = new SearchCriterialDto { Page = 1, PageSize = 1 };
                    criterial.SearchFieldList.Add(new KeyDto { Key = "DepartmentIds", Value = departmentId });
                    int totalRecord = 0;

                    var dto = DepartmentService.Instance.GetDepartmentList(criterial, ref totalRecord).FirstOrDefault();

                    if (dto != null && !string.IsNullOrEmpty(dto.DepartmentId) )
                    {
                        string msg = "Department ID already existed!";
                        return Json(msg, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            catch (Exception ex)
            {
                LogHelper.Error("Method: CustomerController - " + System.Reflection.MethodBase.GetCurrentMethod().Name, ex);
            }

            return Json("1", JsonRequestBehavior.AllowGet);
        }
    }
}

AAT/Views/Department/DepartmentList.cshtml
@using Newtonsoft.Json
@using AAT.Model
@using AAT.Model.Utils

@model AAT.Model.ViewModel.DepartmentListViewModel

@using (Html.BeginForm("DepartmentListAction", "Department", FormMethod.Post, new { @id = "DepartmentForm" }))
{
<div class="pagedetail-container">
	<div style="width:100%;" class="bottomborder"><span id="criterialCollapselnk"><img id="imgCriterialCollapse" class="collapseImg" src="~/Images/expand.svg" /> &nbsp;Criteria</span></div>

	<div id="tbCriterial" style="margin-top:15px; padding-bottom:3px;" class="">
		<table style="width:100%;">
			<tr>
				<td class="colCriterialLabel">Department ID</td>
				<td>
					@Html.TextBox("txtDepartmentId", Model.SearchId)
				</td>
				<td class="colCriterialLabel">Department Name</td>
				<td>
					@Html.TextBox("txtDepartmentName",Model.SearchName)
				</td>
			</tr>
		</table>
		<div style="width:100%; text-align:right; padding-top:5px; ">
			<input id="btnSearch" type="button" value="Search" class="btn btn-outline-primary" />
			<input onclick="GoURL('/Department/DepartmentUpdate')" id="btnNewDepartment" type="button" value="+ New" class="btn btn-outline-primary" />
		</div>
	</div>
	@Html.Hidden("ActionId")
	<br />
	<table class="listview-tb">
		<tr class="headder-row">
			<td>#</td>
			<td>Department ID</td>
			<td>Department Name</td>
			<td></td>
		</tr>
		@if (Model.DepartmentList.Count > 0)
		{
			foreach (var item in Model.DepartmentList)
			{
				<tr class="smalltr">
					<td>@item.RowNum</td>
					<td>@item.DepartmentId</td>
					<td>@item.DepartmentName</td>
					<td class="action-col" style="text-align:right; padding-right:15px;">
						<a href="/Department/DepartmentUpdate?id=@item.DepartmentId">Edit</a>
					</td>
				</tr>
			}
		}
		else
		{
			<tr class="smalltr">
				<td colspan="4" style="text-align:center">No record found!</td>
			</tr>
		}

	</table>
	@*<div>
			@Html.Partial("~/Views/Shared/Pager.cshtml", Model.PagingModel)
		</div>*@

</div>
}

<script>

$(function () {

});

$("#btnSearch").click(function () {
	$("#ActionId").val(2);
	$("#DepartmentForm").submit();
});

$("#btnShow").click(function () {
	$("#ActionId").val(2);
	$("#DepartmentForm").submit();
});

function DepartmentPaging(page) {
	$("#ActionId").val(1);
	$("#Page").val(page);
	$("#DepartmentForm").submit();
	}

	$("#criterialCollapselnk").click(function () {
		criterialCollapse();
	});

	function criterialCollapse() {
		var criterialImg = $('#imgCriterialCollapse');
		var tbCriterial = $('#tbCriterial');

		var imgeSrouce = $('#imgCriterialCollapse').attr('src');

		if (imgeSrouce.indexOf("expand.svg") >= 0) {
			$(criterialImg).attr("src", "/Images/collapse.svg");
			tbCriterial.addClass("hideDisplay");
		}
		else {
			$(criterialImg).attr("src", "/Images/expand.svg");
			tbCriterial.removeClass("hideDisplay");
		}
	}
</script>

AAT/Views/Department/DepartmentUpdate.cshtml
@using Newtonsoft.Json
@using AAT.Model

@model AAT.Model.DepartmentDto
@{
	ViewBag.Title = "ArrowCrest - User";
	string header_title = "Department: Create";

	if (!string.IsNullOrEmpty(Model.DepartmentId))
	{
		header_title = "Department: Update";
	}
}

@using (Html.BeginForm("Update", "Department", FormMethod.Post, new { @id = "departmentUpdateForm" }))
{
	<span class="page-title" style="padding-left:20px;">@header_title</span>

	<br />
	<div class="section_content leftPanel" style="padding-left:20px;">
		@Html.Hidden("hidDepartmentId",Model.DepartmentId)
		<table style="width:100%; ">
			<tr id="message-row" class="hideDisplay">
				<td class="section-label"></td>
				<td class="section-item">
					<span class="error-msg" id="errorMessage"></span>
				</td>
			</tr>
			<tr>
				<td class="section-label">Department ID</td>
				<td class="section-item">
					@Html.TextBox("txtDepartmentID", Model.DepartmentId, new { Style = "width:150px", @maxlength = "50" })
				</td>
			</tr>
			<tr>
				<td class="section-label">Department Name</td>
				<td class="section-item">@Html.TextBox("txtDepartmentName", Model.DepartmentName, new { Style = "width:150px", @maxlength = "50" })</td>
			</tr>
			<tr style=" width:45px;">
				<td></td>
				<td>
					<input type="button" id="btnSave" value="Save" class="btn btn-outline-primary" />
					<input onclick="GoURL('/Department/DepartmentList')" type="button" id="btnClose" value="< Back" class="btn btn-outline-primary" />
				</td>
			</tr>
		</table>
	</div>
}

<script>
	$(function () {
	});

	function DisplayMessage(message) {
		$('#errorMessage').text(message);
		$("#message-row").removeClass("hideDisplay");
	}

	function CheckValidInput() {

		var DepartmentId = $('#txtDepartmentID').val();
		var DepartmentName = $('#txtDepartmentName').val();

		if (DepartmentId === '') {
			DisplayMessage("Please input Department Id!");
			$('#txtDepartmentID').focus();
			return false;
		}

		if (DepartmentName === '') {
			DisplayMessage("Please input Department Name!");
			$('#DepartmentName').focus();
			return false;
		}
		return true;
	}

	$('#btnSave').click(function () {
		var DepartmentId = $('#txtDepartmentID').val();
		var DepartmentName = $('#txtDepartmentName').val();

		if (!CheckValidInput()) {
			return;
		}

		var param = { "departmentId": DepartmentId, "originalId": "@Model.DepartmentId" };

		getServerData('/Department/CheckExistedDepartmentId', param, (function (_this) {
			return function (responseObject) {
				if (responseObject) {
					if (responseObject === '1') {
						$("#departmentUpdateForm").submit();
					}
					else {
						DisplayMessage(responseObject);
						return;
					}
				}
			};
		})(this));
	});
</script>